---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
  label: 
    tier: storage
spec:
  accessModes: 
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
