---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drupal-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      containers:
        -
          image: "mysql:5.7"
          name: cont-drupal-mysql
          ports:
            -
              containerPort: 3306
              name: mysql
              protocol: TCP
          volumeMounts:
            -
              mountPath: /var/lib/mysql
              name: vol-drupal
              subPath: dbdata
          env:
            -
              name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal-mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            -
              name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: drupal-mysql-secret
                  key: MYSQL_DATABASE
            -
              name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: drupal-mysql-secret
                  key: MYSQL_USER
      volumes:
        -
          name: vol-drupal
          persistentVolumeClaim:
            claimName: drupal-mysql-pvc
