--- 
# Imperative command:
## kubectl create secret generic drupal-mysql-secret --from-literal=MYSQL_ROOT_PASSWORD=root_password --from-literal=MYSQL_DATABASE=drupal-database --from-literal=MYSQL_USER=root
# Generate the base64 encoded entries with:
# echo -n 'SOME_STRING_HERE' | base64
apiVersion: v1
kind: Secret
metadata:
  name: drupal-mysql-secret
  labels: 
    tier: backend
type: Opaque
data:
  MYSQL_USER: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  MYSQL_DATABASE: ZHJ1cGFsLWRhdGFiYXNl