---
# Impertive Command:
## kubectl expose 
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
  labels: 
    tier: frontend
    app: drupal
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      protocol: TCP
      nodePort: 30095
  selector:
    app: drupal
